name: human-chimp-skeletal-scRNA
output_dir: ../docs
navbar:
  title: human-chimp-skeletal-scRNA
  left:
  - text: Home
    href: index.html
  - text: About
    href: about.html
  - text: License
    href: license.html
  right:
  - icon: fa-github
    text: Source code
    href: https://github.com/ghousman/human-chimp-skeletal-scRNA
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate

theme: jekyll-theme-slate
