---
title: "10x-plot-correlation"
author: "Genevieve Housman"
date: "2/1/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r gene expression correlation across replicates}

#Load libraries
library(Seurat)
library(dplyr)
library(stringi)
library(stringr)
library(ggplot2)
library(colorspace)
library(RColorBrewer)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())


#Load data
data <- readRDS("./data/cellranger-data-full/data.filter.log.indv-cell.int19k-tot.assign.rds") #integrate across individuals - total (15k genes)
#data.ips <- readRDS("./data/cellranger-data-full/data.filter.log.indv-cell.int-t0.assign.rds") #integrate across individuals - Time 0
#data.msc <- readRDS("./data/cellranger-data-full/data.filter.log.indv-cell.int-t1.assign.rds") #integrate across individuals - Time 1
#data.ost <- readRDS("./data/cellranger-data-full/data.filter.log.indv-cell.int-t2.assign.rds") #integrate across individuals - Time 2

#Subset Datasets by Cell Type to Test Correlations

ips <- subset(data.ips, subset=Pair=="H1+C1")
ips1 <- subset(ips, Replicate=="1")
Idents(ips1) <- "rep1"
avg.ips1 <- log1p(AverageExpression(ips1, verbose=FALSE)$RNA)
avg.ips1$gene <- rownames(avg.ips1)
ips2 <- subset(ips, Replicate=="2")
Idents(ips2) <- "rep2"
avg.ips2 <- log1p(AverageExpression(ips2, verbose=FALSE)$RNA)
avg.ips2$gene <- rownames(avg.ips2)
ips.avg <- merge(avg.ips1, avg.ips2, by="gene")
cor(ips.avg$rep1, ips.avg$rep2, method="pearson") #pearson correlation = 0.99
ggplot(ips.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="pink", size=2) +
  labs(x="Average Gene Expression in Replicate 1",y="Average Gene Expression in Replicate 2")
rm(avg.ips1,avg.ips2,ips.avg)

ips1h <- subset(ips1, species=="Human")
Idents(ips1h) <- "rep1"
avg.ips1h <- log1p(AverageExpression(ips1h, verbose=FALSE)$RNA)
avg.ips1h$gene <- rownames(avg.ips1h)
ips2h <- subset(ips2, species=="Human")
Idents(ips2h) <- "rep2"
avg.ips2h <- log1p(AverageExpression(ips2h, verbose=FALSE)$RNA)
avg.ips2h$gene <- rownames(avg.ips2h)
ips.h.avg <- merge(avg.ips1h, avg.ips2h, by="gene")
cor(ips.h.avg$rep1, ips.h.avg$rep2, method="pearson") #pearson correlation = 0.98
ggplot(ips.h.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="pink", size=2) +
  labs(x="Average Gene Expression in Replicate 1 (Human)",y="Average Gene Expression in Replicate 2 (Human)")
rm(avg.ips1h,avg.ips2h,ips.h.avg)

ips1c <- subset(ips1, species=="Chimp")
Idents(ips1c) <- "rep1"
avg.ips1c <- log1p(AverageExpression(ips1c, verbose=FALSE)$RNA)
avg.ips1c$gene <- rownames(avg.ips1c)
ips2c <- subset(ips2, species=="Chimp")
Idents(ips2c) <- "rep2"
avg.ips2c <- log1p(AverageExpression(ips2c, verbose=FALSE)$RNA)
avg.ips2c$gene <- rownames(avg.ips2c)
ips.c.avg <- merge(avg.ips1c, avg.ips2c, by="gene")
cor(ips.c.avg$rep1, ips.c.avg$rep2, method="pearson") #pearson correlation = 0.99
ggplot(ips.c.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="pink", size=2) +
  labs(x="Average Gene Expression in Replicate 1 (Chimp)",y="Average Gene Expression in Replicate 2 (Chimp)")
rm(avg.ips1c,avg.ips2c,ips.c.avg)

rm(ips,ips1,ips2,ips1h,ips2h,ips1c,ips2c)


msc <- subset(data.msc, subset=Pair=="H1+C1")
msc1 <- subset(msc, Replicate=="1")
Idents(msc1) <- "rep1"
avg.msc1 <- log1p(AverageExpression(msc1, verbose=FALSE)$RNA)
avg.msc1$gene <- rownames(avg.msc1)
msc2 <- subset(msc, Replicate=="2")
Idents(msc2) <- "rep2"
avg.msc2 <- log1p(AverageExpression(msc2, verbose=FALSE)$RNA)
avg.msc2$gene <- rownames(avg.msc2)
msc.avg <- merge(avg.msc1, avg.msc2, by="gene")
cor(msc.avg$rep1, msc.avg$rep2, method="pearson") #pearson correlation = 0.97
ggplot(msc.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="mediumorchid", size=2) +
  labs(x="Average Gene Expression in Replicate 1",y="Average Gene Expression in Replicate 2")
rm(avg.msc1,avg.msc2,msc.avg)

msc1h <- subset(msc1, species=="Human")
Idents(msc1h) <- "rep1"
avg.msc1h <- log1p(AverageExpression(msc1h, verbose=FALSE)$RNA)
avg.msc1h$gene <- rownames(avg.msc1h)
msc2h <- subset(msc2, species=="Human")
Idents(msc2h) <- "rep2"
avg.msc2h <- log1p(AverageExpression(msc2h, verbose=FALSE)$RNA)
avg.msc2h$gene <- rownames(avg.msc2h)
msc.h.avg <- merge(avg.msc1h, avg.msc2h, by="gene")
cor(msc.h.avg$rep1, msc.h.avg$rep2, method="pearson") #pearson correlation = 0.98
ggplot(msc.h.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="mediumorchid", size=2) +
  labs(x="Average Gene Expression in Replicate 1 (Human)",y="Average Gene Expression in Replicate 2 (Human)")
rm(avg.msc1h,avg.msc2h,msc.h.avg)

msc1c <- subset(msc1, species=="Chimp")
Idents(msc1c) <- "rep1"
avg.msc1c <- log1p(AverageExpression(msc1c, verbose=FALSE)$RNA)
avg.msc1c$gene <- rownames(avg.msc1c)
msc2c <- subset(msc2, species=="Chimp")
Idents(msc2c) <- "rep2"
avg.msc2c <- log1p(AverageExpression(msc2c, verbose=FALSE)$RNA)
avg.msc2c$gene <- rownames(avg.msc2c)
msc.c.avg <- merge(avg.msc1c, avg.msc2c, by="gene")
cor(msc.c.avg$rep1, msc.c.avg$rep2, method="pearson") #pearson correlation = 0.92
ggplot(msc.c.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="mediumorchid", size=2) +
  labs(x="Average Gene Expression in Replicate 1 (Chimp)",y="Average Gene Expression in Replicate 2 (Chimp)")
rm(avg.msc1c,avg.msc2c,msc.c.avg)

rm(msc,msc1,msc2,msc1h,msc2h,msc1c,msc2c)


ost <- subset(data.ost, subset=Pair=="H1+C1")
ost1 <- subset(ost, Replicate=="1")
Idents(ost1) <- "rep1"
avg.ost1 <- log1p(AverageExpression(ost1, verbose=FALSE)$RNA)
avg.ost1$gene <- rownames(avg.ost1)
ost2 <- subset(ost, Replicate=="2")
Idents(ost2) <- "rep2"
avg.ost2 <- log1p(AverageExpression(ost2, verbose=FALSE)$RNA)
avg.ost2$gene <- rownames(avg.ost2)
ost.avg <- merge(avg.ost1, avg.ost2, by="gene")
cor(ost.avg$rep1, ost.avg$rep2, method="pearson") #pearson correlation = 0.95
ggplot(ost.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="dodgerblue", size=2) +
  labs(x="Average Gene Expression in Replicate 1",y="Average Gene Expression in Replicate 2")
rm(avg.ost1,avg.ost2,ost.avg)

ost1h <- subset(ost1, species=="Human")
Idents(ost1h) <- "rep1"
avg.ost1h <- log1p(AverageExpression(ost1h, verbose=FALSE)$RNA)
avg.ost1h$gene <- rownames(avg.ost1h)
ost2h <- subset(ost2, species=="Human")
Idents(ost2h) <- "rep2"
avg.ost2h <- log1p(AverageExpression(ost2h, verbose=FALSE)$RNA)
avg.ost2h$gene <- rownames(avg.ost2h)
ost.h.avg <- merge(avg.ost1h, avg.ost2h, by="gene")
cor(ost.h.avg$rep1, ost.h.avg$rep2, method="pearson") #pearson correlation = 0.98
ggplot(ost.h.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="dodgerblue", size=2) +
  labs(x="Average Gene Expression in Replicate 1 (Human)",y="Average Gene Expression in Replicate 2 (Human)")
rm(avg.ost1h,avg.ost2h,ost.h.avg)

ost1c <- subset(ost1, species=="Chimp")
Idents(ost1c) <- "rep1"
avg.ost1c <- log1p(AverageExpression(ost1c, verbose=FALSE)$RNA)
avg.ost1c$gene <- rownames(avg.ost1c)
ost2c <- subset(ost2, species=="Chimp")
Idents(ost2c) <- "rep2"
avg.ost2c <- log1p(AverageExpression(ost2c, verbose=FALSE)$RNA)
avg.ost2c$gene <- rownames(avg.ost2c)
ost.c.avg <- merge(avg.ost1c, avg.ost2c, by="gene")
cor(ost.c.avg$rep1, ost.c.avg$rep2, method="pearson") #pearson correlation = 0.86
ggplot(ost.c.avg, aes(rep1, rep2)) +
  geom_point(size=1) +
  geom_smooth(method=lm, se=FALSE, col="dodgerblue", size=2) +
  labs(x="Average Gene Expression in Replicate 1 (Chimp)",y="Average Gene Expression in Replicate 2 (Chimp)")
rm(avg.ost1c,avg.ost2c,ost.c.avg)

rm(ost,ost1,ost2,ost1h,ost2h,ost1c,ost2c)


rm(data.ips,data.msc,data.ost)

```
