---
title: "temp-code"
author: "Genevieve Housman"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Temporary storage of code that needs to be moved to different .Rmd files.

```{r loop for de analysis}
for (i in subset.list) {
  
  for (j in i) {
    
    cell.assign <- str_split(j,"-")[[1]][1]
    cell.subset <- str_split(j,"-")[[1]][2]
    
    #print(cell.assign)
    
    if (str_count(cell.subset,"_")>=1){
      
      #print(length(str_split(cell.subset,"_")[[1]]))

      if (length(str_split(cell.subset,"_")[[1]])==2) {
        print(str_split(cell.subset,"_")[[1]][1])
        print(str_split(cell.subset,"_")[[1]][2])
      }
      else {
        print(str_split(cell.subset,"_")[[1]][1])
        print(str_split(cell.subset,"_")[[1]][2])
        print(str_split(cell.subset,"_")[[1]][3])
      }
    }

    else {
      #print(j)
    }
  }
}
```

```{r process scRNA data - filter out mitochondrial genes from data}

### NO LONGER NEED TO REMOVE MITO GENES FOR ORTHO-EXON V2 ###

#Read in files
data <- readRDS("./data/cellranger-data-full/data.rds")

#Remove mitochondrial genes
mito <- c("MT-ATP6","MT-ATP8","MT-CO1","MT-CO2","MT-CO3","MT-CYB","MT-ND1","MT-ND2","MT-ND3","MT-ND4","MT-ND4L","MT-ND5")
objects <- list()
for (i in 1:length(data))
{
  print(i)
  genes <- which(!(data[[i]]@assays$RNA@counts@Dimnames[[1]] %in% mito))
  obj <- subset(data[[i]], features=genes)
  objects[[i]] <- CreateSeuratObject(obj@assays$RNA@counts, meta.data=obj@meta.data)
}
rm(data,obj)

#Save data
saveRDS(objects, file="./data/cellranger-data-full/data.rds")

```

```{r examine batch effects - merged data vs. integrated data}

### SHOULD BE INCORPORATED TO DATA QC AFTER MERGING AND INTEGRATING DATA ###

#Load libraries
library(Seurat)
library(dplyr)
library(stringi)
library(stringr)
library(ggplot2)
library(colorspace)
library(RColorBrewer)

#Define main directory
dir <- '/project2/gilad/ghousman/skeletal-human-chimp/'

#Load batch info
batch <- read.csv(file=paste0(dir,'human-chimp-skeletal-scRNA/data/scrna-batch.csv'), header=TRUE, sep=",")

#Read and Visualize data (batch of interest: species, Pair, Individual, Cell.Type, Replicate, MSCmedia)

#combine ipscs from all samples
data.ipsc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.merge.ipsc.rds"))             #merge
spps.ipsc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.spps-cell.log.int.ipsc.rds")) #integrate across species
pair.ipsc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.pair-cell.log.int.ipsc.rds")) #integrate across human-chimp pairs
indv.ipsc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.indv-cell.log.int.ipsc.rds")) #integrate across individuals

CombinePlots(plots=list(DimPlot(data.ipsc,group.by="species"),
                        DimPlot(data.ipsc,group.by="Pair"),
                        DimPlot(data.ipsc,group.by="Individual"),
                        DimPlot(data.ipsc,group.by="Cell.Type"),
                        DimPlot(data.ipsc,group.by="Replicate"),
                        DimPlot(data.ipsc,group.by="MSCmedia"),

                        DimPlot(spps.ipsc,group.by="species"),
                        DimPlot(spps.ipsc,group.by="Pair"),
                        DimPlot(spps.ipsc,group.by="Individual"),
                        DimPlot(spps.ipsc,group.by="Cell.Type"),
                        DimPlot(spps.ipsc,group.by="Replicate"),
                        DimPlot(spps.ipsc,group.by="MSCmedia"),
                        
                        DimPlot(pair.ipsc,group.by="species"),
                        DimPlot(pair.ipsc,group.by="Pair"),
                        DimPlot(pair.ipsc,group.by="Individual"),
                        DimPlot(pair.ipsc,group.by="Cell.Type"),
                        DimPlot(pair.ipsc,group.by="Replicate"),
                        DimPlot(pair.ipsc,group.by="MSCmedia"),
                        
                        DimPlot(indv.ipsc,group.by="species"),
                        DimPlot(indv.ipsc,group.by="Pair"),
                        DimPlot(indv.ipsc,group.by="Individual"),
                        DimPlot(indv.ipsc,group.by="Cell.Type"),
                        DimPlot(indv.ipsc,group.by="Replicate"),
                        DimPlot(indv.ipsc,group.by="MSCmedia")), ncol=5)

CombinePlots(plots=list(DimPlot(data.ipsc,group.by="species",reduction='pca'),
                        DimPlot(data.ipsc,group.by="Collection",reduction='pca'),
                        DimPlot(data.ipsc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(data.ipsc,group.by="Samples",reduction='pca'),
                        DimPlot(data.ipsc,group.by="Replicate",reduction='pca'),

                        DimPlot(spps.ipsc,group.by="species",reduction='pca'),
                        DimPlot(spps.ipsc,group.by="Pair",reduction='pca'),
                        DimPlot(spps.ipsc,group.by="Individual",reduction='pca'),
                        DimPlot(spps.ipsc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(spps.ipsc,group.by="Replicate",reduction='pca'),
                        DimPlot(spps.ipsc,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(pair.ipsc,group.by="species",reduction='pca'),
                        DimPlot(pair.ipsc,group.by="Pair",reduction='pca'),
                        DimPlot(pair.ipsc,group.by="Individual",reduction='pca'),
                        DimPlot(pair.ipsc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(pair.ipsc,group.by="Replicate",reduction='pca'),
                        DimPlot(pair.ipsc,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(indv.ipsc,group.by="species",reduction='pca'),
                        DimPlot(indv.ipsc,group.by="Pair",reduction='pca'),
                        DimPlot(indv.ipsc,group.by="Individual",reduction='pca'),
                        DimPlot(indv.ipsc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(indv.ipsc,group.by="Replicate",reduction='pca'),
                        DimPlot(indv.ipsc,group.by="MSCmedia",reduction='pca')), ncol=6)

CombinePlots(plots=list(VlnPlot(data.ipsc,'nCount_RNA',group.by='species'),
                        VlnPlot(spps.ipsc,'nCount_RNA',group.by='species'),
                        VlnPlot(pair.ipsc,'nCount_RNA',group.by='species'),
                        VlnPlot(indv.ipsc,'nCount_RNA',group.by='species'),
                        
                        VlnPlot(data.ipsc,'nFeature_RNA',group.by='species'),
                        VlnPlot(spps.ipsc,'nFeature_RNA',group.by='species'),
                        VlnPlot(pair.ipsc,'nFeature_RNA',group.by='species'),
                        VlnPlot(indv.ipsc,'nFeature_RNA',group.by='species')), ncol=4)

rm(data.ipsc, spps.ipsc, pair.ipsc, indv.ipsc)

#data.ipsc:   species and batches separated           (PC/UMAP separates species, PC/UMAP separates batches)
#spps.ipsc:   species integrated / batches separated  (PC/UMAP separates species)
#pair.ipsc:   species separated / batches integrated  (PC/UMAP separates species)
#indv.ipsc:   species and batches integrated
#NOTES:       UMI and gene counts are higher in humans than chimps


#combine mscs from all samples
data.msc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.merge.msc.rds"))             #merge
spps.msc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.spps-cell.log.int.msc.rds")) #integrate across species
pair.msc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.pair-cell.log.int.msc.rds")) #integrate across human-chimp pairs
indv.msc <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.indv-cell.log.int.msc.rds")) #integrate across individuals

CombinePlots(plots=list(DimPlot(data.msc,group.by="species"),
                        DimPlot(data.msc,group.by="Pair"),
                        DimPlot(data.msc,group.by="Individual"),
                        DimPlot(data.msc,group.by="Cell.Type"),
                        DimPlot(data.msc,group.by="Replicate"),
                        DimPlot(data.msc,group.by="MSCmedia"),

                        DimPlot(spps.msc,group.by="species"),
                        DimPlot(spps.msc,group.by="Pair"),
                        DimPlot(spps.msc,group.by="Individual"),
                        DimPlot(spps.msc,group.by="Cell.Type"),
                        DimPlot(spps.msc,group.by="Replicate"),
                        DimPlot(spps.msc,group.by="MSCmedia"),
                        
                        DimPlot(pair.msc,group.by="species"),
                        DimPlot(pair.msc,group.by="Pair"),
                        DimPlot(pair.msc,group.by="Individual"),
                        DimPlot(pair.msc,group.by="Cell.Type"),
                        DimPlot(pair.msc,group.by="Replicate"),
                        DimPlot(pair.msc,group.by="MSCmedia"),
                        
                        DimPlot(indv.msc,group.by="species"),
                        DimPlot(indv.msc,group.by="Pair"),
                        DimPlot(indv.msc,group.by="Individual"),
                        DimPlot(indv.msc,group.by="Cell.Type"),
                        DimPlot(indv.msc,group.by="Replicate"),
                        DimPlot(indv.msc,group.by="MSCmedia")), ncol=5)

CombinePlots(plots=list(DimPlot(data.msc,group.by="species",reduction='pca'),
                        DimPlot(data.msc,group.by="Collection",reduction='pca'),
                        DimPlot(data.msc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(data.msc,group.by="Samples",reduction='pca'),
                        DimPlot(data.msc,group.by="Replicate",reduction='pca'),

                        DimPlot(spps.msc,group.by="species",reduction='pca'),
                        DimPlot(spps.msc,group.by="Pair",reduction='pca'),
                        DimPlot(spps.msc,group.by="Individual",reduction='pca'),
                        DimPlot(spps.msc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(spps.msc,group.by="Replicate",reduction='pca'),
                        DimPlot(spps.msc,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(pair.msc,group.by="species",reduction='pca'),
                        DimPlot(pair.msc,group.by="Pair",reduction='pca'),
                        DimPlot(pair.msc,group.by="Individual",reduction='pca'),
                        DimPlot(pair.msc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(pair.msc,group.by="Replicate",reduction='pca'),
                        DimPlot(pair.msc,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(indv.msc,group.by="species",reduction='pca'),
                        DimPlot(indv.msc,group.by="Pair",reduction='pca'),
                        DimPlot(indv.msc,group.by="Individual",reduction='pca'),
                        DimPlot(indv.msc,group.by="Cell.Type",reduction='pca'),
                        DimPlot(indv.msc,group.by="Replicate",reduction='pca'),
                        DimPlot(indv.msc,group.by="MSCmedia",reduction='pca')), ncol=6)

CombinePlots(plots=list(VlnPlot(data.msc,'nCount_RNA',group.by='species'),
                        VlnPlot(spps.msc,'nCount_RNA',group.by='species'),
                        VlnPlot(pair.msc,'nCount_RNA',group.by='species'),
                        VlnPlot(indv.msc,'nCount_RNA',group.by='species'),
                        
                        VlnPlot(data.msc,'nFeature_RNA',group.by='species'),
                        VlnPlot(spps.msc,'nFeature_RNA',group.by='species'),
                        VlnPlot(pair.msc,'nFeature_RNA',group.by='species'),
                        VlnPlot(indv.msc,'nFeature_RNA',group.by='species')), ncol=4)

rm(data.msc, spps.msc, pair.msc, indv.msc)

#data.msc:   species and batches separated           (PC/UMAP separates species, PC/UMAP separates batches)
#spps.msc:   species integrated / batches separated  (PC/UMAP separates species)
#pair.msc:   species separated / batches integrated  (PC/UMAP separates species)
#indv.msc:   species and batches integrated
#NOTES:      UMI and gene counts are higher in humans than chimps


#combine osteoblasts from all samples
data.osteo <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.merge.osteo.rds"))             #merge
spps.osteo <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.spps-cell.log.int.osteo.rds")) #integrate across species
pair.osteo <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.pair-cell.log.int.osteo.rds")) #integrate across human-chimp pairs
indv.osteo <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.indv-cell.log.int.osteo.rds")) #integrate across individuals

CombinePlots(plots=list(DimPlot(data.osteo,group.by="species"),
                        DimPlot(data.osteo,group.by="Pair"),
                        DimPlot(data.osteo,group.by="Individual"),
                        DimPlot(data.osteo,group.by="Cell.Type"),
                        DimPlot(data.osteo,group.by="Replicate"),
                        DimPlot(data.osteo,group.by="MSCmedia"),

                        DimPlot(spps.osteo,group.by="species"),
                        DimPlot(spps.osteo,group.by="Pair"),
                        DimPlot(spps.osteo,group.by="Individual"),
                        DimPlot(spps.osteo,group.by="Cell.Type"),
                        DimPlot(spps.osteo,group.by="Replicate"),
                        DimPlot(spps.osteo,group.by="MSCmedia"),
                        
                        DimPlot(pair.osteo,group.by="species"),
                        DimPlot(pair.osteo,group.by="Pair"),
                        DimPlot(pair.osteo,group.by="Individual"),
                        DimPlot(pair.osteo,group.by="Cell.Type"),
                        DimPlot(pair.osteo,group.by="Replicate"),
                        DimPlot(pair.osteo,group.by="MSCmedia"),
                        
                        DimPlot(indv.osteo,group.by="species"),
                        DimPlot(indv.osteo,group.by="Pair"),
                        DimPlot(indv.osteo,group.by="Individual"),
                        DimPlot(indv.osteo,group.by="Cell.Type"),
                        DimPlot(indv.osteo,group.by="Replicate"),
                        DimPlot(indv.osteo,group.by="MSCmedia")), ncol=5)

CombinePlots(plots=list(DimPlot(data.osteo,group.by="species",reduction='pca'),
                        DimPlot(data.osteo,group.by="Collection",reduction='pca'),
                        DimPlot(data.osteo,group.by="Cell.Type",reduction='pca'),
                        DimPlot(data.osteo,group.by="Samples",reduction='pca'),
                        DimPlot(data.osteo,group.by="Replicate",reduction='pca'),

                        DimPlot(spps.osteo,group.by="species",reduction='pca'),
                        DimPlot(spps.osteo,group.by="Pair",reduction='pca'),
                        DimPlot(spps.osteo,group.by="Individual",reduction='pca'),
                        DimPlot(spps.osteo,group.by="Cell.Type",reduction='pca'),
                        DimPlot(spps.osteo,group.by="Replicate",reduction='pca'),
                        DimPlot(spps.osteo,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(pair.osteo,group.by="species",reduction='pca'),
                        DimPlot(pair.osteo,group.by="Pair",reduction='pca'),
                        DimPlot(pair.osteo,group.by="Individual",reduction='pca'),
                        DimPlot(pair.osteo,group.by="Cell.Type",reduction='pca'),
                        DimPlot(pair.osteo,group.by="Replicate",reduction='pca'),
                        DimPlot(pair.osteo,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(indv.osteo,group.by="species",reduction='pca'),
                        DimPlot(indv.osteo,group.by="Pair",reduction='pca'),
                        DimPlot(indv.osteo,group.by="Individual",reduction='pca'),
                        DimPlot(indv.osteo,group.by="Cell.Type",reduction='pca'),
                        DimPlot(indv.osteo,group.by="Replicate",reduction='pca'),
                        DimPlot(indv.osteo,group.by="MSCmedia",reduction='pca')), ncol=6)

CombinePlots(plots=list(VlnPlot(data.osteo,'nCount_RNA',group.by='species'),
                        VlnPlot(spps.osteo,'nCount_RNA',group.by='species'),
                        VlnPlot(pair.osteo,'nCount_RNA',group.by='species'),
                        VlnPlot(indv.osteo,'nCount_RNA',group.by='species'),
                        
                        VlnPlot(data.osteo,'nFeature_RNA',group.by='species'),
                        VlnPlot(spps.osteo,'nFeature_RNA',group.by='species'),
                        VlnPlot(pair.osteo,'nFeature_RNA',group.by='species'),
                        VlnPlot(indv.osteo,'nFeature_RNA',group.by='species')), ncol=4)

rm(data.osteo, spps.osteo, pair.osteo, indv.osteo)

#data.osteo:   species and batches separated           (PC/UMAP separates species, PC/UMAP separates batches)
#spps.osteo:   species integrated / batches separated  (PC/UMAP separates species)
#pair.osteo:   species separated / batches integrated  (PC/UMAP separates species)
#indv.osteo:   species and batches integrated
#NOTES:        UMI and gene counts are higher in humans than chimps


#combine all cells from all samples
data <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.merge.rds"))        #merge
spps <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.spps.log.int.rds")) #integrate across species
pair <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.pair.log.int.rds")) #integrate across human-chimp pairs
indv <- readRDS(paste0(dir,"/human-chimp-skeletal-scRNA/data/cellranger-data-full/data.indv.log.int.rds")) #integrate across individuals

CombinePlots(plots=list(DimPlot(data,group.by="species"),
                        DimPlot(data,group.by="Pair"),
                        DimPlot(data,group.by="Individual"),
                        DimPlot(data,group.by="Cell.Type"),
                        DimPlot(data,group.by="Replicate"),
                        DimPlot(data,group.by="MSCmedia"),

                        DimPlot(spps,group.by="species"),
                        DimPlot(spps,group.by="Pair"),
                        DimPlot(spps,group.by="Individual"),
                        DimPlot(spps,group.by="Cell.Type"),
                        DimPlot(spps,group.by="Replicate"),
                        DimPlot(spps,group.by="MSCmedia"),
                        
                        DimPlot(pair,group.by="species"),
                        DimPlot(pair,group.by="Pair"),
                        DimPlot(pair,group.by="Individual"),
                        DimPlot(pair,group.by="Cell.Type"),
                        DimPlot(pair,group.by="Replicate"),
                        DimPlot(pair,group.by="MSCmedia"),
                        
                        DimPlot(indv,group.by="species"),
                        DimPlot(indv,group.by="Pair"),
                        DimPlot(indv,group.by="Individual"),
                        DimPlot(indv,group.by="Cell.Type"),
                        DimPlot(indv,group.by="Replicate"),
                        DimPlot(indv,group.by="MSCmedia")), ncol=5)

CombinePlots(plots=list(DimPlot(data,group.by="species",reduction='pca'),
                        DimPlot(data,group.by="Collection",reduction='pca'),
                        DimPlot(data,group.by="Cell.Type",reduction='pca'),
                        DimPlot(data,group.by="Samples",reduction='pca'),
                        DimPlot(data,group.by="Replicate",reduction='pca'),

                        DimPlot(spps,group.by="species",reduction='pca'),
                        DimPlot(spps,group.by="Pair",reduction='pca'),
                        DimPlot(spps,group.by="Individual",reduction='pca'),
                        DimPlot(spps,group.by="Cell.Type",reduction='pca'),
                        DimPlot(spps,group.by="Replicate",reduction='pca'),
                        DimPlot(spps,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(pair,group.by="species",reduction='pca'),
                        DimPlot(pair,group.by="Pair",reduction='pca'),
                        DimPlot(pair,group.by="Individual",reduction='pca'),
                        DimPlot(pair,group.by="Cell.Type",reduction='pca'),
                        DimPlot(pair,group.by="Replicate",reduction='pca'),
                        DimPlot(pair,group.by="MSCmedia",reduction='pca'),
                        
                        DimPlot(indv,group.by="species",reduction='pca'),
                        DimPlot(indv,group.by="Pair",reduction='pca'),
                        DimPlot(indv,group.by="Individual",reduction='pca'),
                        DimPlot(indv,group.by="Cell.Type",reduction='pca'),
                        DimPlot(indv,group.by="Replicate",reduction='pca'),
                        DimPlot(indv,group.by="MSCmedia",reduction='pca')), ncol=6)

CombinePlots(plots=list(VlnPlot(data,'nCount_RNA',group.by='species'),
                        VlnPlot(spps,'nCount_RNA',group.by='species'),
                        VlnPlot(pair,'nCount_RNA',group.by='species'),
                        VlnPlot(indv,'nCount_RNA',group.by='species'),
                        
                        VlnPlot(data,'nFeature_RNA',group.by='species'),
                        VlnPlot(spps,'nFeature_RNA',group.by='species'),
                        VlnPlot(pair,'nFeature_RNA',group.by='species'),
                        VlnPlot(indv,'nFeature_RNA',group.by='species'),
                        VlnPlot(int,'nFeature_RNA',group.by='species')), ncol=4)

rm(data, spps, pair, indv)

#data:   species + cell type + batches separated             (PC/UMAP separates species, PC/UMAP separates cell types, PC/UMAP separates batches)
#spps:   cell type + batches separated / species integrated  (PC/UMAP separates cell types, PC/UMAP separates batches)
#pair:   species + cell type separated / batches integrated  (PC/UMAP separates species, PC/UMAP separates cell types)
#indv:   cell type separated / species + batches integrated  (PC/UMAP separates cell types)
#NOTES:  UMI and gene counts are higher in humans than chimps

```

```{r old ad hoc assignments}

hoc.assign <- function(assignments) {
  assignments$assign <- "other"
  i=1
  while(i <= length(rownames(assignments))) {
    if(assignments$POU5F1[i] == 1 & assignments$TDGF1[i] == 1 & assignments$SOX2[i] == 1 & assignments$EPCAM[i] == 1) {assignments$assign[i] <- "iPSC"}
    if(assignments$THY1[i] == 1 & assignments$NT5E[i] == 1 & assignments$ENG[i] == 1 & assignments$CD44[i] == 1 & assignments$ALPL[i] == 0) {assignments$assign[i] <- "MSC"}
    if(assignments$ALPL[i] == 1) {assignments$assign[i] <- "Osteoblast"}
    i=i+1
  }
 return(as.data.frame(assignments$assign, row.names=rownames(assignments)))
}

```

```{r old ost ad hoc assignments}

hoc.assign.5 <- function(assignments) {
  assignments$assign <- "other"
  i=1
  while(i <= length(rownames(assignments))) {
    if(assignments$COL1A1[i]==0 & assignments$COL1A2[i]==0 & assignments$ALPL[i]==0) {assignments$assign[i] <- "not osteogenic"}
    if(assignments$COL1A1[i]==1 & assignments$COL1A2[i]==1 & assignments$ALPL[i]==1 & assignments$POU5F1[i]==0) {
      #strict criteria
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "unknown osteogenic"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "preosteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "embedding osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "mineralizing osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "maturing osteocyte"}
      #lenient criteria
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==0) {assignments$assign[i] <- "x.embedding osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==1 & assignments$BGLAP[i]==1 & assignments$CAPG[i]==1 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.mineralizing osteoblast"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.maturing osteocyte"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==1 & assignments$PHEX[i]==0 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.maturing osteocyte"}
      if(assignments$RUNX2[i]==0 & assignments$BGLAP[i]==0 & assignments$CAPG[i]==0 & assignments$PHEX[i]==1 & assignments$MEPE[i]==1) {assignments$assign[i] <- "x.maturing osteocyte"}
    }
    i=i+1
  }
  return(as.data.frame(assignments$assign, row.names=rownames(assignments)))
}

```
