---
title: "10x-data-conservexp"
author: "Genevieve Housman"
date: "September 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 10X Data Cellranger Analysis - Conserved Expression

Identify expression patterns that are conserved between humans and chimpanzees within different cell classifications.

```{r, message=FALSE}

#Load libraries
library(Seurat)
library(dplyr)
library(stringi)
library(stringr)
library(ggplot2)
library(grid)
library(gbm)
library(colorspace)
library(RColorBrewer)
library(tidyr)
library(UpSetR)
library(reshape2)
library(CountClust)
library(classtpx)
library(edgeR)
library(matrixStats)

```

```{r load data}

#Load data
scrna <- "./data/cellranger-data-full/data.filter.log.indv-cell.int19k-tot.assign.rds" #integrate across individuals - total (15k genes)
#scrna <- "./data/cellranger-data-full/data.filter.log.indv-cell.int-tot.assign.rds" #integrate across individuals - total
#scrna <- "./data/cellranger-data-full/data.filter.log.indv-cell.int-t0.assign.rds" #integrate across individuals - Time 0
#scrna <- "./data/cellranger-data-full/data.filter.log.indv-cell.int-t1.assign.rds" #integrate across individuals - Time 1
#scrna <- "./data/cellranger-data-full/data.filter.log.indv-cell.int-t2.assign.rds" #integrate across individuals - Time 2
data <- readRDS(scrna)
data

#Load DE results
compare1 <- readRDS("./data/de-data/DEedgeR.totcell.filter.pch20.fc.bh.stage.rds")
compare2 <- readRDS("./data/de-data/DEedgeR.totcell.filter.pch20.fc.bh.cluster.rds")
compare3 <- readRDS("./data/de-data/DEedgeR.totcell.filter.pch20.fc.bh.adhoc.rds")
compare4 <- readRDS("./data/de-data/DEedgeR.totcell.filter.pch20.fc.bh.ostadhoc.rds")
DEdata <- rbind(compare1,compare2,compare3,compare4)
rm(compare1,compare2,compare3,compare4)

```

Define genes of interest: all except mitochondrial genes and ribosomal genes

```{r}

genes <- rownames(data@assays$RNA@counts)
genes.mito <- c("MT-ATP6","MT-ATP8","MT-CO1","MT-CO2","MT-CO3","MT-CYB","MT-ND1","MT-ND2","MT-ND3","MT-ND4","MT-ND4L","MT-ND5")
genes.ribo <- grep('^RP',genes,value=T)
genes.no.mito.ribo <- genes[which(!(genes %in% c(genes.mito,genes.ribo)))]
rm(genes,genes.mito,genes.ribo)

```

```{r}

#Define parameters for data processing
subset.list <- list(stage=list("stage-Time 0","stage-Time 1","stage-Time 2"),
                    clust=list("cluster-iPSC.c1","cluster-iPSC.c2","cluster-iPSC.c3","cluster-MSC.c1","cluster-Osteoblast.c1","cluster-Osteoblast.c2"),
                    combI=c("cluster-iPSC.c1_iPSC.c2_iPSC.c3"),
                    combO=c("cluster-Osteoblast.c1_Osteoblast.c2"),
                    adhoc=list("adhoc-iPSC","adhoc-MSC","adhoc-Osteoblast"),
                    ostadhoc=list("ostadhoc-preosteoblast","ostadhoc-embedding osteoblast"))
filter.arg==TRUE
filter.type=="pch"
filter.param=0.2

#Get normalized gene count data
CEdata <- tibble()

for (i in subset.list) {
  
  for (j in i) {
    
    print(j)

    #define cell assignment and subtype of interest
    cell.assign <- str_split(j,"-")[[1]][1]
    cell.subset <- str_split(j,"-")[[1]][2]

    #define data subset
    if (str_count(cell.subset,"_")>=1){
      if (length(str_split(cell.subset,"_")[[1]])==2) {
        dataSub <- subset(data,
                          subset=Cluster==str_split(cell.subset,"_")[[1]][1]|
                            Cluster==str_split(cell.subset,"_")[[1]][2])
      }
      else {
        dataSub <- subset(data,
                          subset=Cluster==str_split(cell.subset,"_")[[1]][1]|
                            Cluster==str_split(cell.subset,"_")[[1]][2]|
                            Cluster==str_split(cell.subset,"_")[[1]][3])
      }
    }
    else {
      if(cell.assign=="stage") { dataSub <- subset(data,subset=Stage==cell.subset) }
      if(cell.assign=="cluster") { dataSub <- subset(data,subset=Cluster==cell.subset) }
      if(cell.assign=="adhoc") { dataSub <- subset(data,subset=AdHoc.Assign==cell.subset) }
      if(cell.assign=="ostadhoc") { dataSub <- subset(data,subset=OstAdHoc.Assign==cell.subset) }
    }

    #compile data for CE genes
    
    #count matrix
    counts <- as.matrix(GetAssayData(dataSub, assay="RNA", slot="counts"))
  
    #remove mitochodrial and ribosomal genes
    counts <- counts[which(rownames(counts) %in% genes.no.mito.ribo),]

    #metadata
    metadata <- dataSub@meta.data[,c("Species","Stage","Cluster","AdHoc.Assign","OstAdHoc.Assign")]
    metadata <- metadata[colnames(counts),]
    
    #make edgeR object
    dge <- DGEList(counts)
    meta_dge <- dge$samples[,c("lib.size","norm.factors")]
    meta_dge <- cbind(meta_dge, metadata)
    dge$samples <- meta_dge
    rm(dataSub,counts,metadata,meta_dge)
  
    #filter genes
    if (filter.arg==TRUE){
      if (filter.type=="min.count"){
        keep <- filterByExpr(dge, group=dge$samples$Species, min.count=filter.param, min.total.count=15)
        table(keep)
        dge <- dge[keep, , keep.lib.sizes=FALSE]
        rm(keep)
      }
      if (filter.type=="pch"){
        dge$counts <- dge$counts[rowSums(dge$counts!=0)>=(filter.param*dim(dge$counts)[2]),]
      }
    }
    
    #normalize data
    dge <- calcNormFactors(dge, method="TMM")
    summary(dge$samples$norm.factors)
    
    data.cpm <- cpm(dge, normalized.lib.sizes=TRUE, log=TRUE, prior=2)
    data.meta <- dge$samples[,c("Species","Stage","Cluster","AdHoc.Assign","OstAdHoc.Assign")]
    
    CEtemp <- tibble(Gene=rownames(data.cpm),
                     cell.assign=rep(cell.assign, dim(data.cpm)[1]),
                     cell.subset=rep(cell.subset, dim(data.cpm)[1]),
                     HumanSumCount=rowSums(data.cpm[,which(data.meta$Species=="Human")]),
                     ChimpSumCount=rowSums(data.cpm[,which(data.meta$Species=="Chimp")]),
                     HumanAvgCount=rowMeans(data.cpm[,which(data.meta$Species=="Human")]),
                     ChimpAvgCount=rowMeans(data.cpm[,which(data.meta$Species=="Chimp")]),
                     HumanVarCount=rowVars(as.matrix(data.cpm[,which(data.meta$Species=="Human")])),
                     ChimpVarCount=rowVars(as.matrix(data.cpm[,which(data.meta$Species=="Chimp")])))
    CEtemp$AbsDiffAvg <- abs(CEtemp$HumanAvgCount - CEtemp$ChimpAvgCount)
    CEtemp$AbsDiffVar <- abs(CEtemp$HumanVarCount - CEtemp$ChimpVarCount)
    
    CEdata = rbind(CEdata,CEtemp)

  }
}


```




```{r expression patterns that are shared}

#Get normalized gene count data
ips.cnts <- as.matrix(GetAssayData(subset(data,subset=Cell.Type=="iPSC"), assay="RNA", slot="counts"))
ips.cnts <- ips.cnts[which(rownames(ips.cnts) %in% genes.no.ribo),]
ips.meta <- data@meta.data[colnames(ips.cnts),c("species","Cell.Type")]
ips.dge <- DGEList(ips.cnts)
meta_dge <- ips.dge$samples[,c("lib.size","norm.factors")]
meta_dge <- cbind(meta_dge, ips.meta)
ips.dge$samples <- meta_dge
keep <- filterByExpr(ips.dge, group=ips.dge$samples$species, min.count=1, min.total.count=15)
table(keep)
ips.dge <- ips.dge[keep, , keep.lib.sizes=FALSE]
ips.dge <- calcNormFactors(ips.dge, method="TMM")
data.ips <- cpm(ips.dge, normalized.lib.sizes=TRUE, log=TRUE, prior=2)
ips.meta <- ips.dge$samples[,c("species","Cell.Type")]

msc.cnts <- as.matrix(GetAssayData(subset(data,subset=Cell.Type=="MSC"), assay="RNA", slot="counts"))
msc.cnts <- msc.cnts[which(rownames(msc.cnts) %in% genes.no.ribo),]
msc.meta <- data@meta.data[colnames(msc.cnts),c("species","Cell.Type")]
msc.dge <- DGEList(msc.cnts)
meta_dge <- msc.dge$samples[,c("lib.size","norm.factors")]
meta_dge <- cbind(meta_dge, msc.meta)
msc.dge$samples <- meta_dge
keep <- filterByExpr(msc.dge, group=msc.dge$samples$species, min.count=1, min.total.count=15)
table(keep)
msc.dge <- msc.dge[keep, , keep.lib.sizes=FALSE]
msc.dge <- calcNormFactors(msc.dge, method="TMM")
data.msc <- cpm(msc.dge, normalized.lib.sizes=TRUE, log=TRUE, prior=2)
msc.meta <- msc.dge$samples[,c("species","Cell.Type")]

ost.cnts <- as.matrix(GetAssayData(subset(data,subset=Cell.Type=="Osteoblast"), assay="RNA", slot="counts"))
ost.cnts <- ost.cnts[which(rownames(ost.cnts) %in% genes.no.ribo),]
ost.meta <- data@meta.data[colnames(ost.cnts),c("species","Cell.Type")]
ost.dge <- DGEList(ost.cnts)
meta_dge <- ost.dge$samples[,c("lib.size","norm.factors")]
meta_dge <- cbind(meta_dge, ost.meta)
ost.dge$samples <- meta_dge
keep <- filterByExpr(ost.dge, group=ost.dge$samples$species, min.count=1, min.total.count=15)
table(keep)
ost.dge <- ost.dge[keep, , keep.lib.sizes=FALSE]
ost.dge <- calcNormFactors(ost.dge, method="TMM")
data.ost <- cpm(ost.dge, normalized.lib.sizes=TRUE, log=TRUE, prior=2)
ost.meta <- ost.dge$samples[,c("species","Cell.Type")]

ips.norm <- tibble(Gene=rownames(data.ips),
                   HumanSumCount=rowSums(data.ips[,which(ips.meta$species=="Human")]),
                   ChimpSumCount=rowSums(data.ips[,which(ips.meta$species=="Chimp")]),
                   HumanAvgCount=rowMeans(data.ips[,which(ips.meta$species=="Human")]),
                   ChimpAvgCount=rowMeans(data.ips[,which(ips.meta$species=="Chimp")]),
                   HumanVarCount=rowVars(as.matrix(data.ips[,which(ips.meta$species=="Human")])),
                   ChimpVarCount=rowVars(as.matrix(data.ips[,which(ips.meta$species=="Chimp")])))
ips.norm$AbsDiffAvg <- abs(ips.norm$HumanAvgCount - ips.norm$ChimpAvgCount)
ips.norm$AbsDiffVar <- abs(ips.norm$HumanVarCount - ips.norm$ChimpVarCount)

msc.norm <- tibble(Gene=rownames(data.msc),
                   HumanSumCount=rowSums(data.msc[,which(msc.meta$species=="Human")]),
                   ChimpSumCount=rowSums(data.msc[,which(msc.meta$species=="Chimp")]),
                   HumanAvgCount=rowMeans(data.msc[,which(msc.meta$species=="Human")]),
                   ChimpAvgCount=rowMeans(data.msc[,which(msc.meta$species=="Chimp")]),
                   HumanVarCount=rowVars(as.matrix(data.msc[,which(msc.meta$species=="Human")])),
                   ChimpVarCount=rowVars(as.matrix(data.msc[,which(msc.meta$species=="Chimp")])))
msc.norm$AbsDiffAvg <- abs(msc.norm$HumanAvgCount - msc.norm$ChimpAvgCount)
msc.norm$AbsDiffVar <- abs(msc.norm$HumanVarCount - msc.norm$ChimpVarCount)

ost.norm <- tibble(Gene=rownames(data.ost),
                   HumanSumCount=rowSums(data.ost[,which(ost.meta$species=="Human")]),
                   ChimpSumCount=rowSums(data.ost[,which(ost.meta$species=="Chimp")]),
                   HumanAvgCount=rowMeans(data.ost[,which(ost.meta$species=="Human")]),
                   ChimpAvgCount=rowMeans(data.ost[,which(ost.meta$species=="Chimp")]),
                   HumanVarCount=rowVars(as.matrix(data.ost[,which(ost.meta$species=="Human")])),
                   ChimpVarCount=rowVars(as.matrix(data.ost[,which(ost.meta$species=="Chimp")])))
ost.norm$AbsDiffAvg <- abs(ost.norm$HumanAvgCount - ost.norm$ChimpAvgCount)
ost.norm$AbsDiffVar <- abs(ost.norm$HumanVarCount - ost.norm$ChimpVarCount)



rm(data.ips,data.msc,data.ost,ips.cnts,ips.meta,ips.dge,msc.cnts,msc.meta,msc.dge,ost.cnts,ost.meta,ost.dge)
rm(meta_dge,keep,genes,genes.ribo,genes.no.ribo)

#Visualize gene similarities
summary(ips.norm$AbsDiffAvg) #1st quartile = 0.047
summary(msc.norm$AbsDiffAvg) #1st quartile = 0.061
summary(ost.norm$AbsDiffAvg) #1st quartile = 0.069
summary(ips.norm$AbsDiffVar) #1st quartile = 0.017
summary(msc.norm$AbsDiffVar) #1st quartile = 0.027
summary(ost.norm$AbsDiffVar) #1st quartile = 0.033

par(mfrow=c(3,3))
hist(log2(ips.norm$AbsDiffAvg))
abline(v=log2(0.05), col="red")
hist(log2(msc.norm$AbsDiffAvg))
abline(v=log2(0.05), col="red")
hist(log2(ost.norm$AbsDiffAvg))
abline(v=log2(0.05), col="red")
hist(log2(ips.norm$AbsDiffVar))
abline(v=log2(0.01), col="red")
hist(log2(msc.norm$AbsDiffVar))
abline(v=log2(0.01), col="red")
hist(log2(ost.norm$AbsDiffVar))
abline(v=log2(0.01), col="red")
plot(log2(ips.norm$AbsDiffAvg), log2(ips.norm$AbsDiffVar))
abline(v=log2(0.05), h=log2(0.01), col="red")
plot(log2(msc.norm$AbsDiffAvg), log2(msc.norm$AbsDiffVar))
abline(v=log2(0.05), h=log2(0.01), col="red")
plot(log2(ost.norm$AbsDiffAvg), log2(ost.norm$AbsDiffVar))
abline(v=log2(0.05), h=log2(0.01), col="red")

ips.norm <- ips.norm[order(ips.norm$HumanSumCount,decreasing=TRUE),]
msc.norm <- msc.norm[order(msc.norm$HumanSumCount,decreasing=TRUE),]
ost.norm <- ost.norm[order(ost.norm$HumanSumCount,decreasing=TRUE),]

ips.genes <- ips.norm %>% 
                dplyr::filter(AbsDiffAvg<0.05 & AbsDiffVar<0.01)
msc.genes <- msc.norm %>% 
                dplyr::filter(AbsDiffAvg<0.05 & AbsDiffVar<0.01)
ost.genes <- ost.norm %>% 
                dplyr::filter(AbsDiffAvg<0.05 & AbsDiffVar<0.01)

par(mfrow=c(2,3))
plot(ips.norm$HumanSumCount, ips.norm$AbsDiffVar, xlim=c(100000,200000))
plot(msc.norm$HumanSumCount, msc.norm$AbsDiffVar, xlim=c(130000,240000))
plot(ost.norm$HumanSumCount, ost.norm$AbsDiffVar, xlim=c(80000,150000))
plot(ips.genes$HumanSumCount, ips.genes$AbsDiffVar, xlim=c(100000,200000))
plot(msc.genes$HumanSumCount, msc.genes$AbsDiffVar, xlim=c(130000,240000))
plot(ost.genes$HumanSumCount, ost.genes$AbsDiffVar, xlim=c(80000,150000))

intersect(ips.genes$Gene, msc.genes$Gene) #shared genes: DEK, SEC11C, WDR33
intersect(ips.genes$Gene, ost.genes$Gene) #shared genes: none
intersect(msc.genes$Gene, ost.genes$Gene) #shared genes: none

ips.genes <- ips.norm %>% 
                dplyr::filter(AbsDiffAvg<0.05 & AbsDiffVar<0.01) %>% 
                dplyr::filter(Gene %in% rownames(data@assays$integrated))
msc.genes <- msc.norm %>% 
                dplyr::filter(AbsDiffAvg<0.05 & AbsDiffVar<0.01) %>% 
                dplyr::filter(Gene %in% rownames(data@assays$integrated))
ost.genes <- ost.norm %>% 
                dplyr::filter(AbsDiffAvg<0.05 & AbsDiffVar<0.01) %>% 
                dplyr::filter(Gene %in% rownames(data@assays$integrated))

VlnPlot(subset(data,subset=Stage=="Time 0"), assay="integrated", slot="data", features=ips.genes$Gene[1:3], pt.size=0)
VlnPlot(subset(data,subset=Stage=="Time 1"), assay="integrated", slot="data", features=msc.genes$Gene[1:3], pt.size=0)
VlnPlot(subset(data,subset=Stage=="Time 2"), assay="integrated", slot="data", features=ost.genes$Gene[1:3], pt.size=0)

VlnPlot(subset(data,subset=Stage=="Time 0"), assay="integrated", slot="data", features=c("DEK","SEC11C","WDR33"), pt.size=0)
VlnPlot(subset(data,subset=Stage=="Time 1"), assay="integrated", slot="data", features=c("DEK","SEC11C","WDR33"), pt.size=0)


```
